### ISSUE TITLE
Emoji显示错误

### ISSUE THREAD

**Issue by zyzsdy** [Shiny-Project/Shiny-chrome-extension#2]
![71itlv vtk rt gvfkst m](https://cloud.githubusercontent.com/assets/5925733/24870554/449d4d9e-1e49-11e7-9cc7-b8a930c729dc.png)
如图，这里本来应该是👳🏿的。

**Comment by Last-Order** [comment]
fixed by da9619b71925fe6dd55ace064ba611df86d8ef72 @ Shiny
